# Generated by Django 4.1 on 2022-09-01 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='SousService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True)),
                ('date_add', models.DateField(auto_now_add=True)),
                ('date_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('picture', models.FileField(upload_to='img_service')),
                ('libele', models.TextField()),
                ('description', models.TextField()),
                ('order', models.IntegerField()),
                ('price', models.CharField(max_length=10)),
                ('sous_service_slug', models.SlugField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_service', to='app.service')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
    ]
